# TODO
path: example  # directory containing input files
study_names: ['cooldown']  # names of studies to fit (null for all or list of strings e.g. ['spot00', 'spot01'])
idxs: null  # indices of files to fit (null for all or list of indices e.g. [1, 2, 3])

# Signal Processing
signal_process:
  heterodyne: di-homodyne  # detection method: 'di-homodyne' or 'mono-homodyne'
  null_point: 2  # null point selection (valid range: 1-4)
  plot: true  # enable/disable processed signal visualization

# FFT Analysis
fft:
  signal_proportion: 0.9  # proportion of signal to analyze (0.0 to 1.0)
  use_derivative: true  # use signal derivative instead of raw signal
  analysis_type: psd  # analysis method: 'psd' (power spectral density) or 'fft' (fast Fourier transform)

# Lorentzian Fitting
lorentzian:
  signal_proportion: 1.0  # proportion of signal to use for fitting (0.0 to 1.0)
  frequency_bounds: [0.1, 0.9]  # frequency range for fitting [GHz]
  dc_filter_range: [0, 12000]  # DC filtering range [Hz]
  bimodal_fit: false  # enable bimodal Lorentzian fitting
  plot: true  # enable/disable FFT and Lorentzian fit visualization

# TGS Fitting
tgs:
  grating_spacing: 3.5276  # TGS probe grating spacing [µm]
  signal_proportion: 0.9  # proportion of signal to use for fitting (0.0 to 1.0)
  maxfev: 100000  # Maximum number of iterations for final functional fit
  plot: true  # enable/disable TGS fit visualization